# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yamlt

trigger:
- master



pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '12.x'
#   displayName: 'Install Node.js'

# - script: |
#     ls
#     npm install
#   displayName: 'npm install and build'

# - task: CopyFiles@2
#   inputs:
#     sourceFolder: '$(Build.SourcesDirectory)'
#     contents: '*.tgz' 
#     targetFolder: $(Build.ArtifactStagingDirectory)/npm
#   displayName: 'Copy npm package'

- task: CopyFiles@2
  inputs:
    sourceFolder: '.'
    # contents: 'package.json' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy code'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: be-api
  displayName: 'Publish npm artifact'


# # - deployment: VMDeploy
#   runs-on: ubuntu-latest
#   displayName: Build Maven Project
#   # pool:
#   #   vmImage: 'ubuntu-latest'
#   environment:
#     name: dev
#     resourceType: VirtualMachine
#   strategy:
#     runOnce:
#       deploy:
#         steps:
#         - script: echo my first deployment